apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-image-tag
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaceSelector:
                matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: NotIn
                    values: [kube-system, kube-public, kyverno]
      validate:
        message: "Image tag ':latest' or missing tag is not allowed. Use a specific version tag."
        pattern:
          spec:
            containers:
              - image: "?*:?*"
            =(initContainers):
              - image: "?*:?*"
